const DEFAULT_ENDPOINT = "/";

const SERVICE_ENDPOINT = "/services/getall";
const SERVICE_GET_BY_ID_ENDPOINT = "/services/get/";
const SERVICE_PAGE_ENDPOINT = "/services";
const SERVICE_CREATE_ENDPOINTS = "/services/create";
const SERVICE_EDIT_ENDPOINTS = "/services/edit/";
const SERVICE_DELETE_ENDPOINTS = "/services/delete/";

const SAVE_CLOUD_JS = "/save-cloud.js";

const ABOUT_PAGE_ENDPOINT = "/about";
const ABOUT_GET_ENDPOINT = "/about/getall";
const ABOUT_CREATE_ENDPOINT = "/about/create";

const SKILLS_PAGE_ENDPOINT = "/skills";
const SKILLS_GET_ENDPOINT = "/skills/getall";
const SKILLS_CREATE_ENDPOINT = "/skills/create";
const SKILLS_GET_BY_ID_ENDPOINT = "/skills/get/";
const SKILLS_UPDATE_ENDPOINT = "/skills/update/";
const SKILLS_DELETE_ENDPOINT = "/skills/delete/";

const PORTFOLIO_PAGE_ENDPOINT = "/portfolio";
const PORTFOLIO_GET_ENDPOINT = "/portfolio/getall";
const PORTFOLIO_CREATE_ENDPOINT = "/portfolio/create";

const TESTIMONIAL_PAGE_ENDPOINT = "/testimonial";
const TESTIMONIAL_GET_ALL_ENDPOINT = "/testimonial/getall";
const TESTIMONIAL_CREATE_ENDPOINT = "/testimonial/create";

const APPLICATION_ENDPOINT = "/application";
const APPLICATION_GET_ALL_ENDPOINT = "/application/getall";
const APPLICATION_CREATE_ENDPOINT = "/application/create";

const CONTACT_PAGE_ENDPOINT = "/contact";
const CONTACT_GET_ALL_ENDPOINT = "/contact/getall";
const CONTACT_CREATE_ENDPOINT = "/contact/create";

module.exports = {
  DEFAULT_ENDPOINT,
  SERVICE_ENDPOINT,
  SERVICE_CREATE_ENDPOINTS,
  SERVICE_PAGE_ENDPOINT,
  SERVICE_EDIT_ENDPOINTS,
  SERVICE_DELETE_ENDPOINTS,
  ABOUT_PAGE_ENDPOINT,
  SKILLS_PAGE_ENDPOINT,
  PORTFOLIO_PAGE_ENDPOINT,
  TESTIMONIAL_PAGE_ENDPOINT,
  SAVE_CLOUD_JS,
  SERVICE_GET_BY_ID_ENDPOINT,
  ABOUT_GET_ENDPOINT,
  ABOUT_CREATE_ENDPOINT,
  SKILLS_GET_ENDPOINT,
  SKILLS_CREATE_ENDPOINT,
  SKILLS_GET_BY_ID_ENDPOINT,
  SKILLS_UPDATE_ENDPOINT,
  SKILLS_DELETE_ENDPOINT,
  PORTFOLIO_GET_ENDPOINT,
  PORTFOLIO_CREATE_ENDPOINT,
  TESTIMONIAL_GET_ALL_ENDPOINT,
  TESTIMONIAL_CREATE_ENDPOINT,
  APPLICATION_ENDPOINT,
  APPLICATION_GET_ALL_ENDPOINT,
  APPLICATION_CREATE_ENDPOINT,
  CONTACT_PAGE_ENDPOINT,
  CONTACT_GET_ALL_ENDPOINT,
  CONTACT_CREATE_ENDPOINT,
};
